/** Analysis category: tables, their cells, statistics and windows. */
import { define, menu, numIn, pick, textIn } from '../spec.ts';
import { Order } from '../../codegen/order.ts';
import { quote } from '../../codegen/quote.ts';

const STATS: Array<[string, string]> = [
  ['합계', 'sum'],
  ['평균', 'average'],
  ['최댓값', 'maximum'],
  ['최솟값', 'minimum'],
  ['표준편차', 'stdev'],
  ['중앙값', 'median'],
];

define(
  {
    type: 'table_value',
    category: 'analysis',
    message: '테이블 %1 의 %2 행 %3 열의 값',
    args: [pick('TABLE', 'table'), numIn('ROW', 1), textIn('COLUMN', '값')],
    shape: 'value',
    order: Order.ATOMIC,
    code: (a) => [`${a.TABLE}[${a.ROW}, ${a.COLUMN}]`, Order.ATOMIC],
  },
  {
    type: 'table_set_value',
    category: 'analysis',
    message: '테이블 %1 의 %2 행 %3 열을 %4 로 바꾸기',
    args: [pick('TABLE', 'table'), numIn('ROW', 1), textIn('COLUMN', '값'), textIn('VALUE', '10')],
    shape: 'statement',
    code: (a) => `${a.TABLE}[${a.ROW}, ${a.COLUMN}] = ${a.VALUE}`,
  },
  {
    type: 'table_size',
    category: 'analysis',
    message: '테이블 %1 의 %2',
    args: [pick('TABLE', 'table'), menu('OF', [['행 개수', 'row_count'], ['열 개수', 'column_count']])],
    shape: 'value',
    order: Order.ATOMIC,
    code: (a) => [`${a.OF}(${a.TABLE})`, Order.ATOMIC],
  },
  {
    type: 'table_add_line',
    category: 'analysis',
    message: '테이블 %1 에 %2 추가하기',
    args: [pick('TABLE', 'table'), menu('LINE', [['행', 'row'], ['열', 'column']])],
    shape: 'statement',
    code: (a) => `in ${a.TABLE} add ${a.LINE}`,
  },
  {
    type: 'table_insert_line',
    category: 'analysis',
    message: '테이블 %1 의 %2 번째에 %3 추가하기',
    args: [pick('TABLE', 'table'), numIn('INDEX', 1), menu('LINE', [['행', 'row'], ['열', 'column']])],
    shape: 'statement',
    code: (a) => `in ${a.TABLE} insert ${a.LINE} at ${a.INDEX}`,
  },
  {
    type: 'table_remove_line',
    category: 'analysis',
    message: '테이블 %1 의 %2 번째 %3 삭제하기',
    args: [pick('TABLE', 'table'), numIn('INDEX', 1), menu('LINE', [['행', 'row'], ['열', 'column']])],
    shape: 'statement',
    code: (a) => `remove ${a.TABLE} ${a.LINE} ${a.INDEX}`,
  },
  {
    type: 'table_stat',
    category: 'analysis',
    message: '테이블 %1 의 %2 열의 %3',
    args: [pick('TABLE', 'table'), textIn('COLUMN', '값'), menu('STAT', STATS)],
    shape: 'value',
    order: Order.ATOMIC,
    code: (a) => [`${a.STAT}(${a.TABLE}, ${a.COLUMN})`, Order.ATOMIC],
  },
  {
    type: 'table_last_row',
    category: 'analysis',
    message: '테이블 %1 의 %2 열의 마지막 값',
    args: [pick('TABLE', 'table'), textIn('COLUMN', '값')],
    shape: 'value',
    order: Order.ATOMIC,
    code: (a) => [`last_row(${a.TABLE}, ${a.COLUMN})`, Order.ATOMIC],
  },
  {
    type: 'table_correlation',
    category: 'analysis',
    message: '테이블 %1 의 %2 열과 %3 열의 상관계수',
    args: [pick('TABLE', 'table'), textIn('A', '이름'), textIn('B', '값')],
    shape: 'value',
    order: Order.ATOMIC,
    code: (a) => [`correlation(${a.TABLE}, ${a.A}, ${a.B})`, Order.ATOMIC],
  },
  {
    type: 'table_lookup',
    category: 'analysis',
    message: '테이블 %1 에서 %2 열이 %3 인 행의 %4 열 값',
    args: [pick('TABLE', 'table'), textIn('KEY', '이름'), textIn('VALUE', '가'), textIn('COLUMN', '값')],
    shape: 'value',
    order: Order.ATOMIC,
    code: (a) => [`lookup(${a.TABLE}, ${a.KEY}, ${a.VALUE}, ${a.COLUMN})`, Order.ATOMIC],
  },
  {
    type: 'table_show',
    category: 'analysis',
    message: '테이블 %1 창 %2',
    args: [pick('TABLE', 'table'), menu('MODE', [['열기', 'show'], ['닫기', 'hide']])],
    shape: 'statement',
    code: (a) => `${a.MODE} ${a.TABLE}`,
  },
  {
    type: 'table_show_for',
    category: 'analysis',
    message: '테이블 %1 창을 %2 초 동안 열기',
    args: [pick('TABLE', 'table'), numIn('SECS', 3)],
    shape: 'statement',
    code: (a) => `show ${a.TABLE} for ${a.SECS}`,
  },
  {
    type: 'table_show_chart',
    category: 'analysis',
    message: '테이블 %1 의 %2 번째 차트 열기',
    args: [pick('TABLE', 'table'), numIn('INDEX', 1)],
    shape: 'statement',
    code: (a) => `show ${a.TABLE} chart ${a.INDEX}`,
  },
  {
    type: 'table_hide_chart',
    category: 'analysis',
    message: '테이블 창 닫기',
    args: [],
    shape: 'statement',
    code: () => 'hide chart',
  },
  {
    type: 'table_save',
    category: 'analysis',
    message: '테이블 %1 저장하기',
    args: [pick('TABLE', 'table')],
    shape: 'statement',
    code: (a) => `save ${a.TABLE}`,
  },
);
