/** Brush category: pen colour, thickness, drawing and stamping. */
import { colourField, define, menu, numIn } from '../spec.ts';

define(
  {
    type: 'brush_start',
    category: 'brush',
    message: '그리기 시작하기',
    args: [],
    shape: 'statement',
    code: () => 'start draw',
  },
  {
    type: 'brush_stop',
    category: 'brush',
    message: '그리기 멈추기',
    args: [],
    shape: 'statement',
    code: () => 'stop draw',
  },
  {
    type: 'brush_stamp',
    category: 'brush',
    message: '도장 찍기',
    args: [],
    shape: 'statement',
    code: () => 'stamp',
  },
  {
    type: 'brush_clear',
    category: 'brush',
    message: '모든 붓 지우기',
    args: [],
    shape: 'statement',
    code: () => 'clear draw',
  },
  {
    type: 'brush_set_colour',
    category: 'brush',
    message: '붓의 색을 %1 (으)로 정하기',
    args: [colourField('COLOUR', '#ff0000')],
    shape: 'statement',
    code: (a) => `draw_color = ${a.COLOUR}`,
  },
  {
    type: 'brush_random_colour',
    category: 'brush',
    message: '붓의 색을 무작위로 정하기',
    args: [],
    shape: 'statement',
    code: () => 'draw_color = random_color()',
  },
  {
    type: 'brush_set_width',
    category: 'brush',
    message: '붓의 굵기를 %1 (으)로 정하기',
    args: [numIn('VALUE', 1)],
    shape: 'statement',
    code: (a) => `draw_width = ${a.VALUE}`,
  },
  {
    type: 'brush_change_width',
    category: 'brush',
    message: '붓의 굵기를 %1 만큼 바꾸기',
    args: [numIn('VALUE', 1)],
    shape: 'statement',
    code: (a) => `draw_width += ${a.VALUE}`,
  },
  {
    type: 'brush_set_alpha',
    category: 'brush',
    message: '붓의 투명도를 %1 (으)로 정하기',
    args: [numIn('VALUE', 50)],
    shape: 'statement',
    code: (a) => `draw_alpha = ${a.VALUE}`,
  },
  {
    type: 'brush_change_alpha',
    category: 'brush',
    message: '붓의 투명도를 %1 만큼 바꾸기',
    args: [numIn('VALUE', 10)],
    shape: 'statement',
    code: (a) => `draw_alpha += ${a.VALUE}`,
  },
  {
    type: 'brush_set_fill',
    category: 'brush',
    message: '채우기 색을 %1 (으)로 정하기',
    args: [colourField('COLOUR', '#0000ff')],
    shape: 'statement',
    code: (a) => `fill_color = ${a.COLOUR}`,
  },
  {
    type: 'brush_fill',
    category: 'brush',
    message: '채우기 %1',
    args: [menu('MODE', [['시작하기', 'start'], ['멈추기', 'stop']])],
    shape: 'statement',
    code: (a) => `${a.MODE} fill`,
  },
);
