/** Data category: variables, lists and the answer box. */
import { define, menu, numIn, pick, textIn } from '../spec.ts';
import { Order } from '../../codegen/order.ts';

define(
  {
    type: 'data_variable',
    category: 'data',
    message: '%1 값',
    args: [pick('NAME', 'variable')],
    shape: 'value',
    order: Order.ATOMIC,
    code: (a) => [a.NAME, Order.ATOMIC],
  },
  {
    type: 'data_set_variable',
    category: 'data',
    message: '%1 를 %2 (으)로 정하기',
    args: [pick('NAME', 'variable'), textIn('VALUE', '10')],
    shape: 'statement',
    code: (a) => `${a.NAME} = ${a.VALUE}`,
  },
  {
    type: 'data_change_variable',
    category: 'data',
    message: '%1 에 %2 만큼 더하기',
    args: [pick('NAME', 'variable'), numIn('VALUE', 10)],
    shape: 'statement',
    code: (a) => `${a.NAME} += ${a.VALUE}`,
  },
  {
    type: 'data_variable_visible',
    category: 'data',
    message: '변수 %1 %2',
    args: [pick('NAME', 'variable'), menu('MODE', [['보이기', 'show'], ['숨기기', 'hide']])],
    shape: 'statement',
    code: (a) => `${a.MODE} ${a.NAME}`,
  },
  {
    type: 'data_list_item',
    category: 'data',
    message: '%1 의 %2 번째 항목',
    args: [pick('NAME', 'list'), numIn('INDEX', 1)],
    shape: 'value',
    order: Order.ATOMIC,
    code: (a) => [`${a.NAME}[${a.INDEX}]`, Order.ATOMIC],
  },
  {
    type: 'data_list_length',
    category: 'data',
    message: '%1 의 항목 수',
    args: [pick('NAME', 'list')],
    shape: 'value',
    order: Order.ATOMIC,
    code: (a) => [`length(${a.NAME})`, Order.ATOMIC],
  },
  {
    type: 'data_list_contains',
    category: 'data',
    message: '%1 에 %2 이(가) 포함되어 있는가?',
    args: [pick('NAME', 'list'), textIn('VALUE', '10')],
    shape: 'boolean',
    order: Order.ATOMIC,
    code: (a) => [`contains(${a.NAME}, ${a.VALUE})`, Order.ATOMIC],
  },
  {
    type: 'data_list_add',
    category: 'data',
    message: '%1 에 %2 추가하기',
    args: [pick('NAME', 'list'), textIn('VALUE', '10')],
    shape: 'statement',
    code: (a) => `in ${a.NAME} add ${a.VALUE}`,
  },
  {
    type: 'data_list_insert',
    category: 'data',
    message: '%1 의 %2 번째에 %3 넣기',
    args: [pick('NAME', 'list'), numIn('INDEX', 1), textIn('VALUE', '10')],
    shape: 'statement',
    code: (a) => `in ${a.NAME} insert ${a.VALUE} at ${a.INDEX}`,
  },
  {
    type: 'data_list_remove',
    category: 'data',
    message: '%1 의 %2 번째 항목 삭제하기',
    args: [pick('NAME', 'list'), numIn('INDEX', 1)],
    shape: 'statement',
    code: (a) => `remove ${a.NAME}[${a.INDEX}]`,
  },
  {
    type: 'data_list_replace',
    category: 'data',
    message: '%1 의 %2 번째 항목을 %3 로 바꾸기',
    args: [pick('NAME', 'list'), numIn('INDEX', 1), textIn('VALUE', '10')],
    shape: 'statement',
    code: (a) => `${a.NAME}[${a.INDEX}] = ${a.VALUE}`,
  },
  {
    type: 'data_list_visible',
    category: 'data',
    message: '리스트 %1 %2',
    args: [pick('NAME', 'list'), menu('MODE', [['보이기', 'show'], ['숨기기', 'hide']])],
    shape: 'statement',
    code: (a) => `${a.MODE} ${a.NAME}`,
  },
  {
    type: 'data_ask',
    category: 'data',
    message: '%1 을(를) 묻고 대답 기다리기',
    args: [textIn('QUESTION', '이름이 뭐야?')],
    shape: 'statement',
    code: (a) => `ask ${a.QUESTION}`,
  },
  {
    type: 'data_answer',
    category: 'data',
    message: '대답',
    args: [],
    shape: 'value',
    order: Order.ATOMIC,
    code: () => ['answer', Order.ATOMIC],
  },
  {
    type: 'data_answer_visible',
    category: 'data',
    message: '대답 %1',
    args: [menu('MODE', [['보이기', 'show'], ['숨기기', 'hide']])],
    shape: 'statement',
    code: (a) => `${a.MODE} answer`,
  },
);
