/** Flow category: waits, loops, branches, stopping and cloning. */
import { boolIn, define, menu, numIn, pick, stack } from '../spec.ts';
import { quote } from '../../codegen/quote.ts';

define(
  {
    type: 'flow_wait',
    category: 'flow',
    message: '%1 초 기다리기',
    args: [numIn('SECS', 2)],
    shape: 'statement',
    code: (a) => `wait ${a.SECS}`,
  },
  {
    type: 'flow_wait_until',
    category: 'flow',
    message: '%1 이(가) 될 때까지 기다리기',
    args: [boolIn('COND')],
    shape: 'statement',
    code: (a) => `wait ${a.COND}`,
  },
  {
    type: 'flow_repeat',
    category: 'flow',
    message: '%1 번 반복하기 %2',
    args: [numIn('TIMES', 10), stack()],
    shape: 'statement',
    code: (a) => `repeat ${a.TIMES}:\n${a.BODY}end`,
  },
  {
    type: 'flow_forever',
    category: 'flow',
    message: '계속 반복하기 %1',
    args: [stack()],
    shape: 'statement',
    code: (a) => `forever:\n${a.BODY}end`,
  },
  {
    type: 'flow_repeat_while',
    category: 'flow',
    message: '%1 인 동안 반복하기 %2',
    args: [boolIn('COND'), stack()],
    shape: 'statement',
    code: (a) => `while ${a.COND}:\n${a.BODY}end`,
  },
  {
    type: 'flow_repeat_until',
    category: 'flow',
    message: '%1 이(가) 될 때까지 반복하기 %2',
    args: [boolIn('COND'), stack()],
    shape: 'statement',
    code: (a) => `until ${a.COND}:\n${a.BODY}end`,
  },
  {
    type: 'flow_break',
    category: 'flow',
    message: '반복 중단하기',
    args: [],
    shape: 'statement',
    code: () => 'break',
  },
  {
    type: 'flow_continue',
    category: 'flow',
    message: '다음 반복으로 넘어가기',
    args: [],
    shape: 'statement',
    code: () => 'continue',
  },
  {
    type: 'flow_skip',
    category: 'flow',
    message: '기다리지 않고 다음 반복으로 넘어가기',
    args: [],
    shape: 'statement',
    code: () => 'skip',
  },
  {
    type: 'flow_if',
    category: 'flow',
    message: '만일 %1 이라면 %2',
    args: [boolIn('COND'), stack()],
    shape: 'statement',
    code: (a) => `if ${a.COND}:\n${a.BODY}end`,
  },
  {
    type: 'flow_if_else',
    category: 'flow',
    message: '만일 %1 이라면 %2 아니면 %3',
    args: [boolIn('COND'), stack('BODY'), stack('ELSE')],
    shape: 'statement',
    code: (a) => `if ${a.COND}:\n${a.BODY}else:\n${a.ELSE}end`,
  },
  {
    type: 'flow_stop',
    category: 'flow',
    message: '%1 코드 멈추기',
    args: [
      menu('TARGET', [
        ['자신의 이', 'this'],
        ['자신의 다른', 'other'],
        ['자신의 모든', 'me'],
        ['이 오브젝트의 모든', 'object'],
        ['다른 오브젝트의 모든', 'them'],
        ['모든', 'all'],
      ]),
    ],
    shape: 'statement',
    code: (a) => (a.TARGET === 'this' ? 'stop' : `stop ${a.TARGET}`),
  },
  {
    type: 'flow_stop_project',
    category: 'flow',
    message: '작품 정지하기',
    args: [],
    shape: 'statement',
    code: () => 'stop project',
  },
  {
    type: 'flow_restart',
    category: 'flow',
    message: '처음부터 다시 실행하기',
    args: [],
    shape: 'statement',
    code: () => 'restart',
  },
  {
    type: 'flow_clone',
    category: 'flow',
    message: '%1 의 복제본 만들기',
    args: [pick('TARGET', 'cloneTarget')],
    shape: 'statement',
    code: (a) => (a.TARGET === 'self' ? 'clone' : `clone ${quote(a.TARGET)}`),
  },
  {
    type: 'flow_delete_clone',
    category: 'flow',
    message: '이 복제본 삭제하기',
    args: [],
    shape: 'statement',
    code: () => 'del clone',
  },
  {
    type: 'flow_delete_clones',
    category: 'flow',
    message: '모든 복제본 삭제하기',
    args: [],
    shape: 'statement',
    code: () => 'del clones',
  },
);
