/** Looks category: visibility, costumes, speech bubbles, size and effects. */
import { define, menu, numIn, pick, textIn } from '../spec.ts';
import { quote } from '../../codegen/quote.ts';

const EFFECTS: Array<[string, string]> = [
  ['색깔', 'effect_color'],
  ['밝기', 'effect_brightness'],
  ['투명도', 'effect_alpha'],
];

define(
  {
    type: 'looks_show',
    category: 'looks',
    message: '모양 보이기',
    args: [],
    shape: 'statement',
    code: () => 'show',
  },
  {
    type: 'looks_hide',
    category: 'looks',
    message: '모양 숨기기',
    args: [],
    shape: 'statement',
    code: () => 'hide',
  },
  {
    type: 'looks_set_costume',
    category: 'looks',
    message: '%1 모양으로 바꾸기',
    args: [pick('COSTUME', 'costume')],
    shape: 'statement',
    code: (a) => `costume = ${quote(a.COSTUME)}`,
  },
  {
    type: 'looks_next_costume',
    category: 'looks',
    message: '다음 모양으로 바꾸기',
    args: [],
    shape: 'statement',
    code: () => 'next costume',
  },
  {
    type: 'looks_prev_costume',
    category: 'looks',
    message: '이전 모양으로 바꾸기',
    args: [],
    shape: 'statement',
    code: () => 'prev costume',
  },
  {
    type: 'looks_say',
    category: 'looks',
    message: '%1 말하기',
    args: [textIn('TEXT', '안녕!')],
    shape: 'statement',
    code: (a) => `say ${a.TEXT}`,
  },
  {
    type: 'looks_say_for',
    category: 'looks',
    message: '%1 을(를) %2 초 동안 말하기',
    args: [textIn('TEXT', '안녕!'), numIn('SECS', 4)],
    shape: 'statement',
    code: (a) => `say ${a.TEXT} for ${a.SECS}`,
  },
  {
    type: 'looks_think',
    category: 'looks',
    message: '%1 생각하기',
    args: [textIn('TEXT', '음...')],
    shape: 'statement',
    code: (a) => `think ${a.TEXT}`,
  },
  {
    type: 'looks_think_for',
    category: 'looks',
    message: '%1 을(를) %2 초 동안 생각하기',
    args: [textIn('TEXT', '음...'), numIn('SECS', 4)],
    shape: 'statement',
    code: (a) => `think ${a.TEXT} for ${a.SECS}`,
  },
  {
    type: 'looks_clear_bubble',
    category: 'looks',
    message: '말풍선 지우기',
    args: [],
    shape: 'statement',
    code: () => 'clear bubble',
  },
  {
    type: 'looks_set_size',
    category: 'looks',
    message: '크기를 %1 (으)로 정하기',
    args: [numIn('VALUE', 100)],
    shape: 'statement',
    code: (a) => `size = ${a.VALUE}`,
  },
  {
    type: 'looks_change_size',
    category: 'looks',
    message: '크기를 %1 만큼 바꾸기',
    args: [numIn('VALUE', 10)],
    shape: 'statement',
    code: (a) => `size += ${a.VALUE}`,
  },
  {
    type: 'looks_set_scale',
    category: 'looks',
    message: '%1 비율을 %2 (으)로 정하기',
    args: [menu('AXIS', [['가로', 'scale_x'], ['세로', 'scale_y']]), numIn('VALUE', 100)],
    shape: 'statement',
    code: (a) => `${a.AXIS} = ${a.VALUE}`,
  },
  {
    type: 'looks_change_scale',
    category: 'looks',
    message: '%1 비율을 %2 만큼 바꾸기',
    args: [menu('AXIS', [['가로', 'scale_x'], ['세로', 'scale_y']]), numIn('VALUE', 10)],
    shape: 'statement',
    code: (a) => `${a.AXIS} += ${a.VALUE}`,
  },
  {
    type: 'looks_reset_size',
    category: 'looks',
    message: '원래 크기로 되돌리기',
    args: [],
    shape: 'statement',
    code: () => 'reset size',
  },
  {
    type: 'looks_set_effect',
    category: 'looks',
    message: '%1 효과를 %2 (으)로 정하기',
    args: [menu('EFFECT', EFFECTS), numIn('VALUE', 100)],
    shape: 'statement',
    code: (a) => `${a.EFFECT} = ${a.VALUE}`,
  },
  {
    type: 'looks_change_effect',
    category: 'looks',
    message: '%1 효과를 %2 만큼 주기',
    args: [menu('EFFECT', EFFECTS), numIn('VALUE', 10)],
    shape: 'statement',
    code: (a) => `${a.EFFECT} += ${a.VALUE}`,
  },
  {
    type: 'looks_clear_effect',
    category: 'looks',
    message: '효과 모두 지우기',
    args: [],
    shape: 'statement',
    code: () => 'clear effects',
  },
  {
    type: 'looks_flip',
    category: 'looks',
    message: '%1 모양 뒤집기',
    args: [menu('AXIS', [['좌우', 'x'], ['상하', 'y']])],
    shape: 'statement',
    code: (a) => `flip ${a.AXIS}`,
  },
  {
    type: 'looks_order',
    category: 'looks',
    message: '%1 보내기',
    args: [
      menu('ORDER', [
        ['맨 앞으로', 'first'],
        ['앞으로', 'front'],
        ['뒤로', 'back'],
        ['맨 뒤로', 'last'],
      ]),
    ],
    shape: 'statement',
    code: (a) => `order ${a.ORDER}`,
  },
);
