/** Moving category: steps, points, rotation and coordinates. */
import { define, numIn, pick } from '../spec.ts';
import { Order } from '../../codegen/order.ts';
import { quote } from '../../codegen/quote.ts';

/** Two-value forms take their arguments side by side, so each one binds tight. */
const POS = Order.UNARY;

define(
  {
    type: 'moving_forward',
    category: 'moving',
    message: '이동 방향으로 %1 만큼 움직이기',
    args: [numIn('STEPS', 10)],
    shape: 'statement',
    code: (a) => `forward ${a.STEPS}`,
  },
  {
    type: 'moving_forward_at',
    category: 'moving',
    message: '%1 도 방향으로 %2 만큼 움직이기',
    args: [numIn('ANGLE', 90), numIn('STEPS', 10)],
    shape: 'statement',
    code: (a) => `forward ${a.STEPS} at ${a.ANGLE}`,
  },
  {
    type: 'moving_move_xy',
    category: 'moving',
    message: '좌표를 x %1 y %2 만큼 바꾸기',
    args: [numIn('X', 10, POS), numIn('Y', 10, POS)],
    shape: 'statement',
    code: (a) => `move ${a.X} ${a.Y}`,
  },
  {
    type: 'moving_move_xy_time',
    category: 'moving',
    message: '%1 초 동안 좌표를 x %2 y %3 만큼 바꾸기',
    args: [numIn('SECS', 2), numIn('X', 10, POS), numIn('Y', 10, POS)],
    shape: 'statement',
    code: (a) => `move ${a.X} ${a.Y} in ${a.SECS}`,
  },
  {
    type: 'moving_goto_xy',
    category: 'moving',
    message: '좌표 x %1 y %2 위치로 이동하기',
    args: [numIn('X', 0, POS), numIn('Y', 0, POS)],
    shape: 'statement',
    code: (a) => `go ${a.X} ${a.Y}`,
  },
  {
    type: 'moving_goto_xy_time',
    category: 'moving',
    message: '%1 초 동안 좌표 x %2 y %3 위치로 이동하기',
    args: [numIn('SECS', 2), numIn('X', 0, POS), numIn('Y', 0, POS)],
    shape: 'statement',
    code: (a) => `go ${a.X} ${a.Y} in ${a.SECS}`,
  },
  {
    type: 'moving_goto_target',
    category: 'moving',
    message: '%1 위치로 이동하기',
    args: [pick('TARGET', 'lookTarget')],
    shape: 'statement',
    code: (a) => `go ${quote(a.TARGET)}`,
  },
  {
    type: 'moving_goto_target_time',
    category: 'moving',
    message: '%1 초 동안 %2 위치로 이동하기',
    args: [numIn('SECS', 2), pick('TARGET', 'lookTarget')],
    shape: 'statement',
    code: (a) => `go ${quote(a.TARGET)} in ${a.SECS}`,
  },
  {
    type: 'moving_bounce',
    category: 'moving',
    message: '화면 끝에 닿으면 튕기기',
    args: [],
    shape: 'statement',
    code: () => 'bounce',
  },
  {
    type: 'moving_turn',
    category: 'moving',
    message: '방향을 %1 만큼 회전하기',
    args: [numIn('ANGLE', 90)],
    shape: 'statement',
    code: (a) => `turn ${a.ANGLE}`,
  },
  {
    type: 'moving_turn_time',
    category: 'moving',
    message: '%1 초 동안 방향을 %2 만큼 회전하기',
    args: [numIn('SECS', 1), numIn('ANGLE', 90)],
    shape: 'statement',
    code: (a) => `turn ${a.ANGLE} in ${a.SECS}`,
  },
  {
    type: 'moving_steer',
    category: 'moving',
    message: '이동 방향을 %1 만큼 회전하기',
    args: [numIn('ANGLE', 90)],
    shape: 'statement',
    code: (a) => `steer ${a.ANGLE}`,
  },
  {
    type: 'moving_steer_time',
    category: 'moving',
    message: '%1 초 동안 이동 방향을 %2 만큼 회전하기',
    args: [numIn('SECS', 1), numIn('ANGLE', 90)],
    shape: 'statement',
    code: (a) => `steer ${a.ANGLE} in ${a.SECS}`,
  },
  {
    type: 'moving_look',
    category: 'moving',
    message: '%1 쪽 바라보기',
    args: [pick('TARGET', 'lookTarget')],
    shape: 'statement',
    code: (a) => `look ${quote(a.TARGET)}`,
  },
  {
    type: 'moving_set_x',
    category: 'moving',
    message: '좌표 x 를 %1 (으)로 정하기',
    args: [numIn('VALUE', 0)],
    shape: 'statement',
    code: (a) => `x = ${a.VALUE}`,
  },
  {
    type: 'moving_change_x',
    category: 'moving',
    message: '좌표 x 를 %1 만큼 바꾸기',
    args: [numIn('VALUE', 10)],
    shape: 'statement',
    code: (a) => `x += ${a.VALUE}`,
  },
  {
    type: 'moving_set_y',
    category: 'moving',
    message: '좌표 y 를 %1 (으)로 정하기',
    args: [numIn('VALUE', 0)],
    shape: 'statement',
    code: (a) => `y = ${a.VALUE}`,
  },
  {
    type: 'moving_change_y',
    category: 'moving',
    message: '좌표 y 를 %1 만큼 바꾸기',
    args: [numIn('VALUE', 10)],
    shape: 'statement',
    code: (a) => `y += ${a.VALUE}`,
  },
  {
    type: 'moving_set_angle',
    category: 'moving',
    message: '방향을 %1 도로 정하기',
    args: [numIn('VALUE', 90)],
    shape: 'statement',
    code: (a) => `angle = ${a.VALUE}`,
  },
  {
    type: 'moving_set_way',
    category: 'moving',
    message: '이동 방향을 %1 도로 정하기',
    args: [numIn('VALUE', 90)],
    shape: 'statement',
    code: (a) => `way = ${a.VALUE}`,
  },
);
