/**
 * Builds the Tess tree-sitter parser to `tree-sitter-tess.wasm`.
 *
 * Writes `src/colors.h` from `@tess/core` first, so the scanner reads colour
 * names from the same table the lexer does.
 */
import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { NAMED_COLORS } from '../../core/src/color.ts';

const here = path.dirname(fileURLToPath(import.meta.url));
const cli = path.resolve(here, '../../../node_modules/.bin/tree-sitter');

const names = Object.keys(NAMED_COLORS).map((name) => name.toLowerCase());
const rows = names.map((name) => `  (const int32_t[]){${[...name].map((c) => c.codePointAt(0)).join(', ')}, 0},`);
fs.writeFileSync(path.join(here, 'src/colors.h'), [
  '/* Generated by build.mjs from @tess/core NAMED_COLORS. Do not edit. */',
  `#define COLOR_NAME_COUNT ${names.length}`,
  'static const int32_t *const COLOR_NAMES[] = {',
  ...rows,
  '};',
  '',
].join('\n'));

execFileSync(cli, ['generate'], { cwd: here, stdio: 'inherit' });
execFileSync(cli, ['build', '--wasm', '-o', 'tree-sitter-tess.wasm'], { cwd: here, stdio: 'inherit' });
